/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiadnvanced_2;

import clases.Producto;
import clases.UnidadMedicion;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author docente
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    //------------
    public ArrayList<Producto> listadoProductos;
    //----------------------------
    public ArrayList<UnidadMedicion> UnidadesMedicion;
    //---------------------
    //Creo el archivo como variable global
    String ruta = "listaProductos.txt";
    public File apuntadorArchivo = new File(ruta);
    public BufferedWriter manejadorArchivo;
    //variables para leeer el archivo
    public FileReader apuntadorLectura = null;
    public BufferedReader manejadorLectura = null;
    //--------
    public int idItemSleccionado=-1;
    //--------
    public Dashboard() throws IOException {
        initComponents();
        //Centrar JFrame
        this.setLocationRelativeTo(null);
        //Asigna cursores a los botones
        this.botonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.botonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        //Curosr para opciones del menù
        this.opcionAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.opcionListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.calculosMercado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        //Botones de la lista
        this.botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.botonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        //----------------------
        this.listadoProductos = new ArrayList<Producto>();
        this.UnidadesMedicion = new ArrayList<UnidadMedicion>();
        /*
        Creo los datos por defecto para la lista de Unidades de medición
        */
        this.UnidadesMedicion.add(new UnidadMedicion("lb", "Libras"));
        this.UnidadesMedicion.add(new UnidadMedicion("oz", "Onzas"));
        this.UnidadesMedicion.add(new UnidadMedicion("kg", "Kilogramos"));
        this.UnidadesMedicion.add(new UnidadMedicion("lt", "Litros"));
        /*Combo Box
        List<String> ls = new ArrayList<String>(); 
        jComboBox.setModel(new DefaultComboBoxModel(ls.toArray()));
        */
        DefaultComboBoxModel datosUnidadMedicion = new DefaultComboBoxModel();
        for (int i = 0; i < this.UnidadesMedicion.size(); i++) {
            datosUnidadMedicion.addElement(this.UnidadesMedicion.get(i).getDetalle()+" ("+this.UnidadesMedicion.get(i).getNombre()+")");
        }
        this.unidadProducto.setModel(datosUnidadMedicion);
        this.unidadProductoEdicion.setModel(datosUnidadMedicion);
        //Mètodo para cargar el archivo al ArrayList y luego a la tabla
        this.cargarDatosDesdeArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuContextual = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JLabel();
        botonMinimizar = new javax.swing.JLabel();
        menuAcciones = new javax.swing.JPanel();
        opcionAgregar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        opcionListar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calculosMercado = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoPrincipal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        contenedorPaneles = new javax.swing.JPanel();
        formularioPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        costoProducto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        unidadProducto = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        Detalle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detalleProducto = new javax.swing.JTextArea();
        guardarProducto = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cantidadProducto = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cuadroMensajes = new javax.swing.JLabel();
        listaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        botonBorrar = new javax.swing.JLabel();
        botonEditar = new javax.swing.JLabel();
        panelMensajeLista = new javax.swing.JPanel();
        cuadroMensajeLista = new javax.swing.JLabel();
        panelCalculos = new javax.swing.JPanel();
        formularioPanelEdicion = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        nombreProductoEdicion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        costoProductoEdicion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        unidadProductoEdicion = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        Detalle1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        detalleProductoEdicion = new javax.swing.JTextArea();
        actualizarProducto = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cantidadProductoEdicion = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        cuadroMensajesEdicion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        menuContextual.setBackground(new java.awt.Color(102, 102, 255));

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_f00d_212947.png"))); // NOI18N
        botonCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
        });

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minus-symbol.png"))); // NOI18N
        botonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuContextualLayout = new javax.swing.GroupLayout(menuContextual);
        menuContextual.setLayout(menuContextualLayout);
        menuContextualLayout.setHorizontalGroup(
            menuContextualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuContextualLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuContextualLayout.setVerticalGroup(
            menuContextualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(botonMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuAcciones.setBackground(new java.awt.Color(102, 102, 255));

        opcionAgregar.setBackground(new java.awt.Color(153, 153, 255));
        opcionAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarPanelAgragar(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseOuHover(evt);
            }
        });
        opcionAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/font-selection-editor.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opcionAgregar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 34));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Agregar Producto");
        opcionAgregar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 0, 210, 34));

        opcionListar.setBackground(new java.awt.Color(153, 153, 255));
        opcionListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarListado(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opcionListarmouseOuHover(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opcionListarmouseHover(evt);
            }
        });
        opcionListar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/list-with-dots.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opcionListar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 34));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Listar Productos");
        opcionListar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 0, 210, 34));

        calculosMercado.setBackground(new java.awt.Color(153, 153, 255));
        calculosMercado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarCalculos(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calculosMercadomouseOuHover(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calculosMercadomouseHover(evt);
            }
        });
        calculosMercado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bar-graph-on-a-rectangle.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calculosMercado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 34));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel7.setText("Facturar");
        calculosMercado.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 0, 206, 34));

        javax.swing.GroupLayout menuAccionesLayout = new javax.swing.GroupLayout(menuAcciones);
        menuAcciones.setLayout(menuAccionesLayout);
        menuAccionesLayout.setHorizontalGroup(
            menuAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(opcionListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(calculosMercado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuAccionesLayout.setVerticalGroup(
            menuAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAccionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(opcionAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculosMercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        logoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cart.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("MERCADO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenedorPaneles.setBackground(new java.awt.Color(204, 204, 255));
        contenedorPaneles.setOpaque(false);
        contenedorPaneles.setLayout(new javax.swing.OverlayLayout(contenedorPaneles));

        formularioPanel.setBackground(new java.awt.Color(20, 111, 208));

        jPanel2.setBackground(new java.awt.Color(20, 111, 208));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Producto");

        nombreProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Valor");

        costoProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Unidad");

        unidadProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        unidadProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unidadProducto, 0, 245, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreProducto)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(costoProducto)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(costoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        jPanel4.setOpaque(false);

        Detalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Detalle.setText("Detalle compra");

        detalleProducto.setColumns(20);
        detalleProducto.setRows(5);
        jScrollPane2.setViewportView(detalleProducto);

        guardarProducto.setBackground(new java.awt.Color(204, 255, 204));
        guardarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check-mark.png"))); // NOI18N
        guardarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarProductoMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Cantidad");

        cantidadProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(Detalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cantidadProducto, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Detalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(guardarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(20, 111, 208));
        jPanel5.setOpaque(false);

        jPanel6.setBackground(new java.awt.Color(20, 111, 208));

        jLabel12.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel12.setText("Adición de Producto");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel7.setBackground(new java.awt.Color(20, 111, 208));

        cuadroMensajes.setText("mensajes del sistema");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cuadroMensajes)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cuadroMensajes)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout formularioPanelLayout = new javax.swing.GroupLayout(formularioPanel);
        formularioPanel.setLayout(formularioPanelLayout);
        formularioPanelLayout.setHorizontalGroup(
            formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formularioPanelLayout.setVerticalGroup(
            formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contenedorPaneles.add(formularioPanel);

        listaPanel.setBackground(new java.awt.Color(20, 111, 208));

        tablaProductos.setBackground(new java.awt.Color(222, 229, 236));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Costo", "Unidad", "Detalle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        botonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBorrarMouseClicked(evt);
            }
        });

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/font-selection-editor.png"))); // NOI18N
        botonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEditarMouseClicked(evt);
            }
        });

        panelMensajeLista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuadroMensajeLista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMensajeLista.add(cuadroMensajeLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        javax.swing.GroupLayout listaPanelLayout = new javax.swing.GroupLayout(listaPanel);
        listaPanel.setLayout(listaPanelLayout);
        listaPanelLayout.setHorizontalGroup(
            listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBorrar)
                        .addGap(6, 6, 6))
                    .addComponent(panelMensajeLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        listaPanelLayout.setVerticalGroup(
            listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMensajeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        contenedorPaneles.add(listaPanel);

        panelCalculos.setBackground(new java.awt.Color(20, 111, 208));

        javax.swing.GroupLayout panelCalculosLayout = new javax.swing.GroupLayout(panelCalculos);
        panelCalculos.setLayout(panelCalculosLayout);
        panelCalculosLayout.setHorizontalGroup(
            panelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        panelCalculosLayout.setVerticalGroup(
            panelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        contenedorPaneles.add(panelCalculos);

        formularioPanelEdicion.setBackground(new java.awt.Color(20, 111, 208));

        jPanel8.setBackground(new java.awt.Color(20, 111, 208));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jPanel9.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Producto");

        nombreProductoEdicion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nombreProductoEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoEdicionActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Valor");

        costoProductoEdicion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Unidad");

        unidadProductoEdicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        unidadProductoEdicion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unidadProductoEdicion, 0, 245, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreProductoEdicion)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(costoProductoEdicion)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreProductoEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(costoProductoEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unidadProductoEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9);

        jPanel14.setOpaque(false);

        Detalle1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Detalle1.setText("Detalle compra");

        detalleProductoEdicion.setColumns(20);
        detalleProductoEdicion.setRows(5);
        jScrollPane3.setViewportView(detalleProductoEdicion);

        actualizarProducto.setBackground(new java.awt.Color(204, 255, 204));
        actualizarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualizarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check-mark.png"))); // NOI18N
        actualizarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarProductoMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Cantidad");

        cantidadProductoEdicion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actualizarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addComponent(Detalle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cantidadProductoEdicion, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(30, 30, 30))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Detalle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidadProductoEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(actualizarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(20, 111, 208));
        jPanel15.setOpaque(false);

        jPanel16.setBackground(new java.awt.Color(20, 111, 208));

        jLabel21.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel21.setText("Edición de Producto");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel17.setBackground(new java.awt.Color(20, 111, 208));

        cuadroMensajesEdicion.setText("mensajes del sistema");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cuadroMensajesEdicion)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cuadroMensajesEdicion)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout formularioPanelEdicionLayout = new javax.swing.GroupLayout(formularioPanelEdicion);
        formularioPanelEdicion.setLayout(formularioPanelEdicionLayout);
        formularioPanelEdicionLayout.setHorizontalGroup(
            formularioPanelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioPanelEdicionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formularioPanelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formularioPanelEdicionLayout.setVerticalGroup(
            formularioPanelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioPanelEdicionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contenedorPaneles.add(formularioPanelEdicion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuContextual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenedorPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuContextual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        // TODO add your handling code here:
        //Cerrrar el Jframe
        this.setVisible(false);
        //Cerrar el APP
        System.exit(0);
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void botonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseClicked
        // TODO add your handling code here:
        //Minimiza mi APP
        this.setExtendedState(1);
    }//GEN-LAST:event_botonMinimizarMouseClicked

    private void mouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseHover
        // TODO add your handling code here:
        this.opcionAgregar.setBackground(new Color(153,48,216));
    }//GEN-LAST:event_mouseHover

    private void mouseOuHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseOuHover
        // TODO add your handling code here:
        this.opcionAgregar.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_mouseOuHover

    private void opcionListarmouseOuHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionListarmouseOuHover
        // TODO add your handling code here:
        this.opcionListar.setBackground(new Color(153,153,255));
        
    }//GEN-LAST:event_opcionListarmouseOuHover

    private void opcionListarmouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionListarmouseHover
        // TODO add your handling code here:
        this.opcionListar.setBackground(new Color(153,48,216));
    }//GEN-LAST:event_opcionListarmouseHover

    private void calculosMercadomouseOuHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculosMercadomouseOuHover
        // TODO add your handling code here:
        this.calculosMercado.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_calculosMercadomouseOuHover

    private void calculosMercadomouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculosMercadomouseHover
        // TODO add your handling code here:
        this.calculosMercado.setBackground(new Color(153,48,216));
    }//GEN-LAST:event_calculosMercadomouseHover

    private void mostrarPanelAgragar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarPanelAgragar
        // TODO add your handling code here:
        this.contenedorPaneles.removeAll();
        this.contenedorPaneles.repaint();
        this.contenedorPaneles.revalidate();
        //--------------
        this.contenedorPaneles.add(this.formularioPanel);
        this.contenedorPaneles.repaint();
        this.contenedorPaneles.revalidate();
    }//GEN-LAST:event_mostrarPanelAgragar

    private void mostrarListado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarListado
        // TODO add your handling code here:
        this.contenedorPaneles.removeAll();
        this.contenedorPaneles.repaint();
        this.contenedorPaneles.revalidate();
        //--------------
        this.contenedorPaneles.add(this.listaPanel);
        this.contenedorPaneles.repaint();
        this.contenedorPaneles.revalidate();
    }//GEN-LAST:event_mostrarListado

    private void mostrarCalculos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarCalculos
        // TODO add your handling code here:
        this.contenedorPaneles.removeAll();
        this.contenedorPaneles.repaint();
        this.contenedorPaneles.revalidate();
        //--------------
        this.contenedorPaneles.add(this.panelCalculos);
        this.contenedorPaneles.repaint();
        this.contenedorPaneles.revalidate();
    }//GEN-LAST:event_mostrarCalculos

    private void guardarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarProductoMouseClicked
        // TODO add your handling code here:
        //Capturar los datos del Producto y agregarlos a la lista
        boolean validacion=validacion();
        //Capturar los datos del porducto y agregarlos a la lista
        if(validacion()){
            //            
            try {            
                this.guardarDatos();
                this.cuadroMensajes.setText("Datos guardados");
            } catch (IOException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.limpiarFormulario();
            
            //------------
            //this.pausaMensaje();
            //------------
            //this.cuadroMensajes.setText("");
        }
        else {
            //Imprimo en consola el error
            System.out.println("Datos Incorrectos");
            JOptionPane.showMessageDialog(this,"Datos Incorrectos","Validacion formulario",JOptionPane.ERROR_MESSAGE);
        }
        //-----------   
    }//GEN-LAST:event_guardarProductoMouseClicked

    private void nombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProductoActionPerformed

    private void botonBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBorrarMouseClicked
        // TODO add your handling code here:
        //Capturamos la fila seleccionada
        int filaSeleccionada=this.tablaProductos.getSelectedRow();
        if(filaSeleccionada>=0){
            //Borrra la fila de la tabla
            ((DefaultTableModel)this.tablaProductos.getModel()).removeRow(filaSeleccionada);
            //Borra fila de la lista
            this.listadoProductos.remove(filaSeleccionada);
        }
        else{
            this.panelMensajeLista.setBackground(Color.red);
            this.cuadroMensajeLista.setText("Debe seleccionar una fila para efectuar el borrado");
        }
    }//GEN-LAST:event_botonBorrarMouseClicked

    private void botonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        //Capturamos la fila seleccionada
        int filaSeleccionada=this.tablaProductos.getSelectedRow();
        this.idItemSleccionado=filaSeleccionada;
        if(filaSeleccionada>=0){                        
            //--Llena el formulario de edcióncon los datos a editar
            Producto productoAEditar = (Producto)this.listadoProductos.get(filaSeleccionada);
            this.nombreProductoEdicion.setText(productoAEditar.getNombre());
            this.costoProductoEdicion.setText(String.valueOf(productoAEditar.getCosto()));
            this.cantidadProductoEdicion.setText(String.valueOf(productoAEditar.getCantidad()));
            this.detalleProductoEdicion.setText(productoAEditar.getDetalle());
            //Asiganar la unidad a través de una busqueda para seccionar el item
            int itemSeleccionado=this.buscarYSeleccionarUnidadMedicion(productoAEditar.getUnidad());
            System.out.println(itemSeleccionado);
            this.unidadProductoEdicion.setSelectedIndex(itemSeleccionado);
            //--Muestra el formulario edición
            this.contenedorPaneles.removeAll();
            this.contenedorPaneles.repaint();
            this.contenedorPaneles.revalidate();
            //--------------
            this.contenedorPaneles.add(this.formularioPanelEdicion);
            this.contenedorPaneles.repaint();
            this.contenedorPaneles.revalidate();
        }
        else{
            this.panelMensajeLista.setBackground(Color.red);
            this.cuadroMensajeLista.setText("Debe seleccionar una fila para efectuar la edición");
        }
    }//GEN-LAST:event_botonEditarMouseClicked

    private void nombreProductoEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProductoEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProductoEdicionActionPerformed

    private void actualizarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarProductoMouseClicked
        // TODO add your handling code here:
        //Capturar los datos del Producto y agregarlos a la lista
        boolean validacion=validacionEdicion();
        //Capturar los datos del porducto y agregarlos a la lista
        if(validacion){
            //            
            try {            
                this.actualizarDatos();
                this.cuadroMensajesEdicion.setText("Datos guardados");
            } catch (IOException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.limpiarFormulario();
            
            //------------
            //this.pausaMensaje();
            //------------
            //this.cuadroMensajes.setText("");
        }
        else {
            //Imprimo en consola el error
            System.out.println("Datos Incorrectos");
            JOptionPane.showMessageDialog(this,"Datos Incorrectos","Validacion formulario",JOptionPane.ERROR_MESSAGE);
        }
        //----------
    }//GEN-LAST:event_actualizarProductoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Dashboard().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    //Validaciones
    private boolean validacion(){
     //Validacion del text cantidad
     boolean vd2=esnumero(this.cantidadProducto.getText());
     //Validacion del text costo
     boolean vd3=esdouble(this.costoProducto.getText());
     //Validacion del text nombre
     boolean vd1=esletra(this.nombreProducto.getText());
     if(vd1 && vd2 && vd3){
         return true;
     }
     else{
         return false;
     }
 }
    private boolean validacionEdicion(){
     //Validacion del text cantidad
     boolean vd2=esnumero(this.cantidadProductoEdicion.getText());
     //Validacion del text costo
     boolean vd3=esdouble(this.costoProductoEdicion.getText());
     //Validacion del text nombre
     boolean vd1=esletra(this.nombreProductoEdicion.getText());
     if(vd1 && vd2 && vd3){
         return true;
     }
     else{
         return false;
     }
 }

    private boolean esnumero(String text) {
        try{
            Integer.parseInt(text);
            return true;
        } catch (Exception e){
            return false;
        }
    }

    private boolean esdouble(String text) {
       try{
           Double.parseDouble(text);
           return true;
       }catch(Exception e){
           return false;
       }
    }

    private boolean esletra(String text) {
       if(text.length()>=3)
           return true;
       else{
           return false;
       }
    }
    private void limpiarFormulario() {
        this.nombreProducto.setText("");
        this.cantidadProducto.setText("");
        this.costoProducto.setText("");
        this.detalleProducto.setText("");
    }
    
    private void forma1AdicionDatos(ArrayList<Producto> listadoProductos) {
        //Renderiza para Jlabel en tabla
        //tablaProductos.setDefaultRenderer(Object.class, new imgTabla());
        //--------
        Object [][]datosTabla = new Object[listadoProductos.size()][6];
        //Recorre el arraylista para adcionar cada fila de este a una fila de la matriz
        for (int i = 0; i < listadoProductos.size(); i++) {
            datosTabla[i][0]=listadoProductos.get(i).getNombre();
            datosTabla[i][1]=String.valueOf(listadoProductos.get(i).getCantidad());
            datosTabla[i][2]=String.valueOf(listadoProductos.get(i).getCosto());
            datosTabla[i][3]=listadoProductos.get(i).getUnidad();
            datosTabla[i][4]=listadoProductos.get(i).getDetalle();
            datosTabla[i][5]=String.valueOf(listadoProductos.get(i).getCantidad()*listadoProductos.get(i).getCosto());
            //----Definiciónde botón
            /*JLabel boton = new JLabel(new ImageIcon(getClass().getResource("/imagenes/list-with-dots.png")));
            boton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void clickBorrar(java.awt.event.MouseEvent evt) {
                    System.out.println("acá adentro");
                }
            });
            //---------------------------
            datosTabla[i][6]=boton;*/
        }
        //A travès de un setModel adiciono el arrayList a la jTable
        //this.tablaProductos.setRowHeight(30);
        this.tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            datosTabla,
            new String [] {
                "Nombre", "Cantidad", "Valor","Unidad","Detalle","Costo"
            }
        ));
        
    }

    private void forma2AdicionDatos(ArrayList<Producto> listadoProductos) {
        //Renderiza para Jlabel en tabla
        //this.tablaProductos.setDefaultRenderer(Object.class, new imgTabla());
        String columnas[]= {"Nombre","Cantidad","Costo","Unidad","Detalle","Costo"};
        /*Creamos un TableModel*/
        DefaultTableModel modeloTabla = new DefaultTableModel(null,columnas);
        //-------
        for (int i = 0; i < listadoProductos.size(); i++) {
            //----Definiciónde botón
            JLabel boton = new JLabel(new ImageIcon(getClass().getResource("/imagenes/list-with-dots.png")));
            Object[] filaAgregar={
                listadoProductos.get(i).getNombre(),
                listadoProductos.get(i).getCantidad(),
                listadoProductos.get(i).getCosto(),
                listadoProductos.get(i).getUnidad(),
                listadoProductos.get(i).getDetalle(),
                listadoProductos.get(i).getCantidad()*listadoProductos.get(i).getCosto()
                //boton
            };
            modeloTabla.addRow(filaAgregar);
        }
        //this.tablaProductos.setRowHeight(30);
        this.tablaProductos.setModel(modeloTabla);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Detalle;
    private javax.swing.JLabel Detalle1;
    private javax.swing.JLabel actualizarProducto;
    private javax.swing.JLabel botonBorrar;
    private javax.swing.JLabel botonCerrar;
    private javax.swing.JLabel botonEditar;
    private javax.swing.JLabel botonMinimizar;
    private javax.swing.JPanel calculosMercado;
    private javax.swing.JTextField cantidadProducto;
    private javax.swing.JTextField cantidadProductoEdicion;
    private javax.swing.JPanel contenedorPaneles;
    private javax.swing.JTextField costoProducto;
    private javax.swing.JTextField costoProductoEdicion;
    private javax.swing.JLabel cuadroMensajeLista;
    private javax.swing.JLabel cuadroMensajes;
    private javax.swing.JLabel cuadroMensajesEdicion;
    private javax.swing.JTextArea detalleProducto;
    private javax.swing.JTextArea detalleProductoEdicion;
    private javax.swing.JPanel formularioPanel;
    private javax.swing.JPanel formularioPanelEdicion;
    private javax.swing.JLabel guardarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel listaPanel;
    private javax.swing.JLabel logoPrincipal;
    private javax.swing.JPanel menuAcciones;
    private javax.swing.JPanel menuContextual;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JTextField nombreProductoEdicion;
    private javax.swing.JPanel opcionAgregar;
    private javax.swing.JPanel opcionListar;
    private javax.swing.JPanel panelCalculos;
    private javax.swing.JPanel panelMensajeLista;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JComboBox<String> unidadProducto;
    private javax.swing.JComboBox<String> unidadProductoEdicion;
    // End of variables declaration//GEN-END:variables

    private void pausaMensaje() {
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {                
                this.mensajeFuturo();
            }

            private void mensajeFuturo() {
                long endTimeMillis = System.currentTimeMillis() + 2000;
                while (true) {
                    // method logic
                    System.out.println("3");
                    if (System.currentTimeMillis() > endTimeMillis) {
                        // do some clean-up
                        System.out.println("4");
                        return;
                    }
                }
            }
        });
        thread.start();
        long endTimeMillis = System.currentTimeMillis() + 2000;
        while (thread.isAlive()) {
            if (System.currentTimeMillis() > endTimeMillis) {
                System.out.println("1");
                break;
            }
            try {
                System.out.println("2");
                Thread.sleep(500);
            }
            catch (InterruptedException t) {}
        }
    }

    private void guardarDatos() throws IOException {
            Producto Productoagregar= new Producto(
                this.nombreProducto.getText(),
                Integer.parseInt(this.cantidadProducto.getText()),
                Double.parseDouble(this.costoProducto.getText()),
                this.unidadProducto.getItemAt(this.unidadProducto.getSelectedIndex()),
                this.detalleProducto.getText()
            );
            this.listadoProductos.add(Productoagregar);
            //------------------
            this.escribirDatosEnArchivo();
            //-------
            //forma2AdicionDatos(this.listadoProductos);
            forma1AdicionDatos(this.listadoProductos);
            //Limpio el formulario
    }

    private void cargarDatosDesdeArchivo() throws FileNotFoundException, IOException {
        //this.manejadorArchivo.
        this.apuntadorLectura = new FileReader (apuntadorArchivo);
        this.manejadorLectura = new BufferedReader(apuntadorLectura);

         // Lectura del fichero
        String linea;
        while((linea=this.manejadorLectura.readLine())!=null){
            //Acá hace un split del archivo
            //-----------------------------
            String[] partes = linea.split(",");
            //Verifica si el archivo tiene al menos un dato
            //System.out.println(partes.length);
            if(partes.length>0){
                //--------
                //Valida que el detalle estè vacìo, si lo està (es null) entonces
                //guarda una cadena vacìa
                if(partes[4].equals("null")){
                   partes[4]="";
                }
                Producto Productoagregar= new Producto(
                    partes[0],
                    Integer.parseInt(partes[1]),
                    Double.parseDouble(partes[2]),
                    partes[3],
                    partes[4]
                );
                //-----
                this.listadoProductos.add(Productoagregar);
                forma1AdicionDatos(this.listadoProductos);
            }
        }
    }

    private void escribirDatosEnArchivo() throws IOException {
        //Me pregunto si el arcivo existe
            if(this.apuntadorArchivo.exists()) {
                this.manejadorArchivo = new BufferedWriter(new FileWriter(this.apuntadorArchivo,false));
            } else {
                this.manejadorArchivo = new BufferedWriter(new FileWriter(this.apuntadorArchivo,false));
            }
            for (int i = 0; i < this.listadoProductos.size(); i++) {   
                Producto itemAgregar=(Producto)this.listadoProductos.get(i);
                this.manejadorArchivo.write(
                    itemAgregar.getNombre()+","+
                    String.valueOf(itemAgregar.getCantidad())+","+
                    String.valueOf(itemAgregar.getCosto())+","+
                    itemAgregar.getUnidad()+","+
                    itemAgregar.getDetalle()
                );
                this.manejadorArchivo.newLine();
            //this.manejadorArchivo.write("\n");             
            }
            this.manejadorArchivo.close();
            //-------
    }

    private int buscarYSeleccionarUnidadMedicion(String unidadSeleccionada) {
        //Debe recorrer la lista de unidades de medición
        for (int i = 0; i < this.UnidadesMedicion.size(); i++) {
            //---------------
            UnidadMedicion itemUnidad=(UnidadMedicion)this.UnidadesMedicion.get(i);
            if(unidadSeleccionada.equals(itemUnidad.getDetalle()+" ("+itemUnidad.getNombre()+")")){
              return i;  
            }
        }
        return -1;
    }

    private void actualizarDatos() throws IOException {
        Producto ProductoEditar= new Producto(
                this.nombreProductoEdicion.getText(),
                Integer.parseInt(this.cantidadProductoEdicion.getText()),
                Double.parseDouble(this.costoProductoEdicion.getText()),
                this.unidadProductoEdicion.getItemAt(this.unidadProductoEdicion.getSelectedIndex()),
                this.detalleProductoEdicion.getText()
            );
            this.listadoProductos.set(this.idItemSleccionado, ProductoEditar);
            //------------------
            this.escribirDatosEnArchivo();
            //-------
            //forma2AdicionDatos(this.listadoProductos);
            forma1AdicionDatos(this.listadoProductos);
            //Limpio el formulario
    }
}
